### ISSUE TITLE
Create a UX live pattern library package inside LMS

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#1058]
As a next step towards consolidating and updating our UX, we intend to create a live pattern library with both exportable sass and preact base components that we can leverage for building the front end IU in LMS and then eventually other projects.  The sass and base components will serve to unify and standardize our UI and also provide default behavior and styling out of the box. They also need to be somewhat customizable in order to capture all the variations of components our pattern library requires. https://hypothesis-pattern-library.netlify.com/

As a first step, we will build a nodejs style package within LMS repo as that will serve as the testing grounds for this effort. In order to speed up the process, we'll build this directly inside LMS, rather than a standalone but with the intent of moving it out to its own repository when it's ready. 

**Requirements**
 
- [ ]  A standalone nodejs package that can export both base components as sass files that lives inside LMS.
- [ ] The base components have their own base styling and props to control variations of styling defined by our pattern lib.
- [ ] Intuitive way to override sass as needed for specialization.
- [ ] May need to consider a layout component to facilitate nesting buttons inside inputs and applying corresponding styling.
- [ ] Components should be well tested

related to https://github.com/hypothesis/pattern-library/issues/1

It may be helpful to model this approach after https://react.semantic-ui.com/

**Comment by robertknight** [comment]
This issue has become obsolete following ongoing work on the @hypothesis/frontend-shared package.
