### ISSUE TITLE
Add a gherkin based test set to cover sections 1-4 of the LTI 1.1 spec

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#1220]
This ticket is being created backwards, as most of this is already done.

## Requirements:

* [x] - We have test coverage of sections 1 - 4
* [x] - The build fails if the tests don't pass - https://github.com/hypothesis/lms/pull/1273
* [x] - The tests test configured assignments - https://github.com/hypothesis/lms/pull/1274
   * Extra credit: also fun with un-configured - Can't see a good way to do this, so going to skip
* [x] - Tests we have duplicated from the functional tests are removed - https://github.com/hypothesis/lms/pull/1275

## Implementation plan:

Split into multiple PRs with:

 * [x] All the fixture `.ini` files and the bin script that generates the `average.ini`'s from them
   *  https://github.com/hypothesis/lms/pull/1231
* [x] The Gherkin scenarios for all the tests, but without any contents yet
    * https://github.com/hypothesis/lms/pull/1233
* [x] Implement the 1.1 test in plain Behave (using step contexts; but not yet HOG)
    * This PR introduces the "step contexts" concept and base class. 
    * Only contains the step contexts needed for 1.1
    * https://github.com/hypothesis/lms/pull/1234
* [x] Higher Order Gerkinify-y the 1.1 test
    * This introduces the HOG concept and adds the HOG code itself. Only contains the feature steps needed for 1.1
   * https://github.com/hypothesis/lms/pull/1235
* [x] Multiple: The rest of the tests 
    * e.g. one PR per section of tests, adding the only what is needed for that section
   * [x] Section 1 - https://github.com/hypothesis/lms/pull/1236
   * [x] Section 2 - https://github.com/hypothesis/lms/pull/1237
   * [x] Section 3 - https://github.com/hypothesis/lms/pull/1238
   * [x] Section 4 - https://github.com/hypothesis/lms/pull/1239

**Comment by jon-betts** [comment]
A PR adding the tests is here: https://github.com/hypothesis/lms/pull/1182

**Comment by jon-betts** [comment]
Tickets have been added to address the outstanding bits, but they need a review etc.

**Comment by jon-betts** [comment]
Finally, I think we're done!
