### ISSUE TITLE
Fact finding for Canvas course sections

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1338]
A research spike to answer a few questions about Canvas course sections integration:

## Canvas Course Sections

How exactly do sections work in Canvas?

Seel also: the [Sections in Canvas and other LMSes](https://docs.google.com/document/d/1sb7ymaOsoDL16M980y-ADfZr8NY9VBv9l40E2dvSWuc/) Google doc

* **When you create a new Canvas course it automatically gets one section**, with the section name being the same as the course name.
* **Each Canvas course always has at least one section**. You can rename the course and/or section so that the section's name no longer matches the course name. But you can't delete the last section--a course must always have at least one section. (You can create a new section and then delete the original first section, though.)
* The default section's name doesn't change if you rename the course after course creation, or vice-versa.
* **Each Canvas user always belongs to at least one section**. They get added to the default section at first. You can add them to a different section and then remove them from the default section. But you can't remove a user from the last section that they still belong to
* **A user can belong to more than one section at once**

## Students

- [x] What do we want students to see?

  When a student launches an assignment the group that will be focused in the client will be the group corresponding to the student's course section.

## Teachers

- [x] What do we want teachers to see?

  When a teacher launches an assignment they will have multiple groups in the client's groups menu: they will see all of the groups for all of the course's sections. The first group (alphabetically) will be initially focused on launch.

  (If the course has only one section then the teacher will see only one group, but the group will be named after the course's one section rather than after the course itself.)

- [x] What about teaching assistants? Same as for teachers.

- [x] What about course observers?  Same as for teachers.

- [x] What about any other non-student roles?  Same as for teachers.

## Getting a user's sections for a course

- [x] Can we get information about the user's course sections, in the LTI launch params? And if so, exactly what info can we get and how?

  - As of 2020-01-16 I think the answer to this is **No**:

    We can use a [Canvas variable substitution](https://canvas.instructure.com/doc/api/file.tools_variable_substitutions.html) to add the current user's course section IDs to the LTI launch params, but this gives us access to the section IDs only not their names, so we'd then have to make Canvas API calls anyway to get the names. Also, this wouldn't work for preexisting installs of our app unless they edited the install's config to add the custom variable substitution.
   -- seanh

- [x] Is there an LTI 1.3-based way to get information about the user's course sections?

  - As of 2020-01-16 I think the answer to this is **No** -- seanh

- [x] Can we get access to information about the user's course sections, from the Canvas API? And if so, exactly what info can we get and how? - Yes, see https://github.com/hypothesis/lms/issues/1403, https://github.com/hypothesis/lms/issues/1404 and https://github.com/hypothesis/lms/issues/1405

See also: [How can an LTI app access course section information?](https://community.canvaslms.com/thread/42081-how-can-an-lti-app-access-course-section-information), a question I asked on the Canvas community forums:

* One response confirmed that LTI 1.1 custom Canvas variable substitutions can be used to get the user's section IDs, but only the IDs.
* The same response said that an LTI 1.3 "LIS claim" can be made or will be able to be made soon, to get section info in the launch params. I don't think this works with Canvas currently
* Another response contradicts this saying "LTI Advantage did not add any new methods of requesting course section information"
* Neither seems to think there's an LTI 1.1-based solution here
* But they did mention that Canvas could enable a section IDs->names mapping in an LTI 1.1 variable expansion for us

## Canvas API Scopes

- [ ] Which new Canvas API scopes will our app need, to support this feature?

- [ ] How can we best handle scoped developer keys that don't give us access to the new APIs that we need to use?

## Section Group IDs

- [x] How can we generate a good unique ID for a Hypothesis group that corresponds to a Canvas course section? Needs to be unique and deterministic. Doesn't need to be human-readable. _See https://github.com/hypothesis/lms/issues/1410_

## Section Group Titles

- [x] How can we generate a good, non-unique, human-readable name for a Hypothesis group that corresponds to a Canvas course section? _See https://github.com/hypothesis/lms/issues/1411_

## Section Changes

- [x] What will we do if a student is removed from a section they previously belonged to (and they may have created annotations in that section's group)? _The student will lose access to any annotations they created in the previous section. If they're added back to the section they will get access to their annotations again.)

- [x] What will we do if a section is deleted (and students may have created annotations in that section's group)? _All students and teachers will permanently lose access to all annotations created in the deleted section._

## SpeedGrader

- [x] How will we handle SpeedGrader? In this case the app is being launched by a teacher, but the annotations that we want to show are in the section(s) that the student being graded belongs to

  Quite a lot of work is needed to make SpeedGrader work with section groups. See https://github.com/hypothesis/lms/pull/1380, https://github.com/hypothesis/lms/issues/1424, https://github.com/hypothesis/lms/issues/1425, and https://github.com/hypothesis/lms/issues/1426

## Backwards Compatibility

- [x] How will we handle preexisting courses (or assignments) that used course groups rather than section groups, and may have annotations in those course groups?

  Assignments that have been previously launched with a course group will somehow have to continue using that course group and not change to section groups, even once the section groups feature is released. Otherwise users would lose access to annotations created in the course grouped. This is tracked on https://github.com/hypothesis/lms/issues/1428

 - [x] How will we handle Canvas application instances that don't have a developer key and secret and therefore can't access the Canvas API? (They will have to retain the old course groups behaviour)

## Showing Groups in the Client

- [x] How can the LMS app tell the client which group to show? In the config that's sent over postMessage

- [x] How can the LMS app get the client to show multiple groups in its groups menu? Already supported in the client

## Canvas API Response Pagination

- [x] How will we handle paginated API responses from Canvas?

  We just need to add support for Canvas API pagination and make multiple requests as necessary. See https://github.com/hypothesis/lms/issues/1406

## Moderation

* Will no longer work
* We'll hide the flag UI
* See: https://hypothes-is.slack.com/archives/CBN3DGW02/p1580142327025200

**Comment by seanh** [comment]
You can get a list of all a given user's sections for a given course (including both the section IDs and the section names) in a single Canvas API call. Like the Canvas Files feature, this will only work for application instances where they've given us a working developer key and secret so that we can use the API.

```terminal
$ http GET 'https://hypothesis.instructure.com/api/v1/courses/<COURSE_ID>?include[]=sections' Authorization:'Bearer 9382~c7I***A8v'
{
  "id": 100,
  "name": "Sections 101",
  ...
  "sections": [
    {
      "id": 107,
      "name": "Section 1",
      "start_at": null,
      "end_at": null,
      "enrollment_role": "StudentEnrollment"
    },
    {
      "id": 108,
      "name": "Section 2",
      "start_at": null,
      "end_at": null,
      "enrollment_role": "StudentEnrollment"
    }
  ],
  ...
}
```

The `<COURSE_ID>` that you need (in the API endpoint's URL) is the `custom_canvas_course_id` launch param.

The sections depend on which user calls the API (which user the given `Authorization` token belongs to). It includes all sections of the course that that user is in.

I'm not sure what happens if a user is a member of a lot of sections (in a single course). Does the list of sections get paginated? But I think we can probably ignore that as it seems like a bizarre edge case.

**Comment by seanh** [comment]
## How the LMS app currently generates the h groupid for a course

* It's generated based entirely on standard LTI launch params

* It's deterministic. Given the same LTI launch params again it will generate the same `groupid`

* It's globally unique: no two courses (either within the same LMS or across different LMS's) will get the same `groupid`

* [`LTILaunchResource.h_groupid()`](https://github.com/hypothesis/lms/blob/6eaab7dbd3128a955ed1f4b61937b2de695a64e7/lms/resources/_lti_launch.py#L101-L116) is the method that generates the `groupid`

* `h_groupid()` just returns `"group:<AUTHORITY_PROVIDED_ID>@<AUTHORITY>"` where:

* `<AUTHORITY>` is the `H_AUTHORITY` deployment setting (e.g. `"lms.hypothes.is"` on production)

* `<AUTHORITY_PROVIDED_ID>` comes from [`LTILaunchResource.h_authority_provided_id()`](https://github.com/hypothesis/lms/blob/6eaab7dbd3128a955ed1f4b61937b2de695a64e7/lms/resources/_lti_launch.py#L75-L99). It's a SHA 1 hash of the standard LTI launch params `"tool_consumer_instance_guid"` (a globally unique ID for the LMS instance, e.g. the particular Canvas site) and `"context_id"` (an ID for the course, unique within the LMS instance).

## Generating the h groupid for a section

The `groupid` for a group corresponding to a Canvas course section must:

* Be deterministic--the same Canvas section must always generate the same `groupid`

* Be globally unique: no two sections (either within the same Canvas site or across different Canvas's) can get the same `groupid`

* Be in the format `group:<AUTHORITY_PROVIDED_ID>@<AUTHORITY>`

* Be globally unique across all h groups. The `@<AUTHORITY>` part means they will never clash with non-LMS groups. The `<AUTHORITY_PROVIDED_ID>` part has to take care of the rest

* The  `@<AUTHORITY>` part must be the `H_AUTHORITY` deployment setting (e.g. `"lms.hypothes.is"` on production)

* The `<AUTHORITY_PROVIDED_ID>` part must:

  * Contain only the characters `[a-zA-Z0-9._\-+!~*()']`

  * Be between 1 and 1024 chars in total

  * Be unique within the LMS authority. That means unique across all sections, courses and LMS's. No two LMS groups can have the same `<AUTHORITY_PROVIDED_ID>` even if they're in different courses or different LMS's

`groupid`'s **don't** need to be short or human-readable.

If Canvas section IDs are unique for the entire Canvas instance (not just the course) then we can replace `h_authority_provided_id()` with one that generates a SHA 1 of the `"tool_consumer_instance_guid"` and the section's ID.

If section IDs are not unique across the entire Canvas site, only unique within the course, then we'll also need `"context_id"` in the SHA-1.

**Comment by seanh** [comment]
## How the LMS app currently generates the h group name for a course

* The group name comes from the [`LTILaunchResource.h_group_name()`](https://github.com/hypothesis/lms/blob/6eaab7dbd3128a955ed1f4b61937b2de695a64e7/lms/resources/_lti_launch.py#L118-L139) method.

* It's based entirely on standard LTI launch params

* It's just the `"context_title"` (course title) launch param truncated to 25 chars with `…`

* Group names do need to be human readable

* Group names do not need to be unique at all

## Generating the h group name for a section

We'll just do exactly the same thing that we do for course names but using the section title from the Canvas API rather than the "context_title"` (course title) launch param.

**Comment by seanh** [comment]
Note to self: need to consider deleted sections and not losing their corresponding groups

**Comment by seanh** [comment]
This fact-finding has been done and we have a working proof-of-concept (https://github.com/hypothesis/lms/pull/1380) and a detailed implementation plan (https://github.com/hypothesis/lms/milestone/10)
