### ISSUE TITLE
Change to using section rather than course groups

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1428]
Depends on:

- [ ] The new Canvas->h sync API: https://github.com/hypothesis/lms/issues/1389
- [ ] Getting the frontend to call the new sync API: https://github.com/hypothesis/lms/issues/1390
- [ ] Getting the frontend to use the groups from the new sync API (sending them to the client): https://github.com/hypothesis/lms/issues/1392
* New Canvas proxy APIs for getting the course sections:
  - [ ] For a student: https://github.com/hypothesis/lms/issues/1403
  - [ ] For a teacher: https://github.com/hypothesis/lms/issues/1404
- [ ] Generating an h group name from a Canvas section: https://github.com/hypothesis/lms/issues/1411
- [ ] Generating an h group ID from a Canvas section: https://github.com/hypothesis/lms/issues/1410
- [ ] "Is a learner?" function: https://github.com/hypothesis/lms/issues/1431
- [ ] Machine user: https://github.com/hypothesis/lms/issues/1400

Change the sync API to fetch the student or teacher's course sections from Canvas (synchronous server-server request), generate the h groups from those sections, upsert those groups into h, and return those groups to the frontend, instead of using a single course group.

### Backwards Compatibility

* Courses that "don't use sections" in Canvas actually have one default section with the same name as the course, and which everyone is a member of. So section groups should work just fine for this kind of course, and appear to function the same as course groups

* This will need to be **feature flagged** and continue using course groups instead of section groups, if the feature flag is off)

* For application instances that don't have a developer key it should continue using course groups 
instead of section groups

* For application instances that do have a developer key **but don't have the necessary API scopes** configured on the key, it should ... ??? Either silently fall back to course groups and/or show some kind of error telling the user that they need to add certain scopes to their dev key

* For pre-existing assignments _that have already been launched with course groups_ it should continue using course groups instead of section groups. This'll require us to implement some way to distinguish assignments that have been launched with a course group already, vs ones that haven't

### Canvas API Scopes

* We need to document the additional Canvas API scopes that we need on this wiki page: https://github.com/hypothesis/lms/wiki/Canvas-API-Endpoints-Used-by-the-Hypothesis-LMS-App

**Comment by seanh** [comment]
I'm gonna close this issue: we ended up with a sync API that always used section groups in the first place, but the use of the sync API is feature flagged. I split out a bunch of separate issues from this one: https://github.com/hypothesis/lms/issues/1695, https://github.com/hypothesis/lms/issues/1696, https://github.com/hypothesis/lms/issues/1697, https://github.com/hypothesis/lms/issues/1698
