### ISSUE TITLE
Make sections work in SpeedGrader

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1694]
When a teacher launches an assignment in SpeedGrader we want the client to show the sections of the student whose submission they're viewing, not the teacher's sections.

We need to:

- [ ] Add the student's `custom_canvas_user_id` to Canvas SpeedGrader submission URLs as a new query param. This was previously its own separate issue: https://github.com/hypothesis/lms/issues/1424

- [ ] Have the backend place the student's `custom_canvas_user_id` from the new query param into the frontend's JS config object. This was previously its own separate issue: https://github.com/hypothesis/lms/issues/1425

- [ ] Have the sync API use the student's groups, not the teachers. This was previously its own separate issue: https://github.com/hypothesis/lms/issues/1426

  Note that the sync API probably doesn't need to actually upsert the section groups into h for SpeedGrader launches: if a student has created any annotations for the assignment in a section group, then that section group must already exist in h. So the sync API just needs to fetch the student's sections (not the teacher's) from the Canvas API and return the correct list of groupids to the frontend (the student's, not the teacher's), the frontend will then pass these to the client.

- [ ] Maintain backwards-compatibility with legacy SpeedGrader URLs that don't have the new params. These should fall back to using the course group
