### ISSUE TITLE
EPIC: Course copy

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#2241]
Now that we have some useful error messages in place for our Canvas users (https://github.com/hypothesis/lms/issues/555), our next steps will be:

- [ ] Meet with Instructure to see if further improvements are possible (i.e., rather than showing an error dialog when instructors & students launch copied assignments created with Canvas Files, can those assignments "just work"?)
- [ ] Investigate why course copy does not work in Moodle and Blackboard (lms/#2218)
- [ ] Get course copy working in Moodle & Blackboard if possible
- [ ] Expand course copy solution to D2L & Sakai if possible

**Comment by seanh** [comment]
I'm gonna close this epic card and use a milestone instead: https://github.com/hypothesis/lms/milestone/20
