### ISSUE TITLE
Add UI for enabling Canvas groups and choosing the group set for an assignment

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2524]
Implement the UI in the assignment configuration app (`FilePickerApp` in the LMS frontend) that allows the user to choose whether groups are enabled for assignment and which group set to use.

UI flow and mocks: https://github.com/hypothesis/lms/issues/2523#issuecomment-821160185

----

**Sub-tasks:**

- [x] Agree on how the frontend should indicate in the generated LTI launch URL whether groups are enabled for an assignment and which Canvas Group Set should be used. _A `group_set` query param will be added to the LTI launch URL if groups are enabled. The value is the ID of the Group Set as returned in the `id` field when the frontend requests the list of available group sets._
- [x] Prototype the whole group set selection flow (https://github.com/hypothesis/lms/pull/2687)
- [x] Extract logic related to "Authorize" button from the Canvas file picker dialog into a separate component so it can be re-used in the groups configuration stage (https://github.com/hypothesis/lms/pull/2700)
- [x] Extract existing functionality out of `FilePickerApp` to avoid it becoming to large to follow: 1) Assignment content selection  (https://github.com/hypothesis/lms/pull/2707), 2) Hidden form field generation (https://github.com/hypothesis/lms/pull/2706)
- [x] Add a new component that allows configuring whether groups are used for an assignment and presents a list of group sets to choose from (https://github.com/hypothesis/lms/pull/2716)
- [x] Set the `group_set` query param in the LTI launch URL to the ID of the chosen group set if groups are enabled for an assignment (https://github.com/hypothesis/lms/pull/2716)
- [x] Refine the basic UI layout to match the mocks in https://github.com/hypothesis/lms/issues/2523#issuecomment-821160185 (https://github.com/hypothesis/lms/pull/2746)
- [x] Fix overflow when assignment URL is long (https://github.com/hypothesis/lms/issues/2774)
- [x] Refine the group set selection UI to look better / match the mocks in https://github.com/hypothesis/lms/issues/2523#issuecomment-821160185

**Comment by lyzadanger** [comment]
Wireframes for this flow (consensus-approved) may be found here: https://github.com/hypothesis/lms/issues/2523

**Comment by robertknight** [comment]
The format for the frontend to pass the chosen group settings back to the backend is discussed [here in Slack](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1621007217483400?thread_ts=1620638554.378200&cid=C1MA4E9B9). We also discussed how to resolve a terminology conflict: Canvas uses the term "Group set" in the UI and "Group category" in the API. 

- We decided to go with the terminology "Group set" rather than "Group category" everywhere. Thinking about future expansion to other LMSes, Blackboard uses "Group set", Moodle uses "Grouping" and D2L uses "Group category", so we'll eventually need to customize the UI text depending on the LMS being used.
- The frontend will add a `group_set` query param to the LTI launch URL submitted back to Canvas with the value equal to the group category/set's `id`, if group sets are enabled for an assignment. If group sets are disabled the parameter will be omitted.

**Comment by robertknight** [comment]
Following the merge of https://github.com/hypothesis/lms/pull/2716 the workflow of enabling group sets for an assignment and selecting a group set is now functional. The initial UI that was added is ugly-but-functional. The remaining task(s) are to polish the UI to be more in line with [these mocks](https://github.com/hypothesis/lms/issues/2523#issuecomment-821160185).

**Comment by robertknight** [comment]
This is almost done now. There are two more changes needed:

- https://github.com/hypothesis/lms/pull/2804
- An update to the @hypothesis/frontend-shared package version used by the LMS to incorporate some checkbox styling improvements

At that point we're done except for any changes arising from internal testing.

**Comment by lyzadanger** [comment]
#2804 is deployed and the `@hypothesis/frontend-shared` package has been versioned and bumped in LMS. We're good here.
