### ISSUE TITLE
Epic: Stabilize and normalize front-end error UI

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#3139]
There are a few disparate tickets regarding symptoms of problematic error presentation in the LMS application, but an epic may be helpful to show how these and some others are related.

The user-facing problems are:

* Some errors are shown with too much or unhelpful information, e.g. https://github.com/hypothesis/lms/issues/2997
* The appearance and structure of errors is inconsistent
* Error dialog sizing is inconsistent and not responsive
* Error and error dialog styling is fragile and hard to extend without breaking something

The immediate causes are:

* There are an awful lot of ways to fry up an error doughnut in the LMS frontend. There are multiple components — `ErrorDisplay`, `ErrorDialog` — that are composed in multiple ways within other error-related components — `ErrorDialogApp`, `LaunchErrorDialog`, `OAuth2RedirectErrorApp` — and some components use `ErrorDisplay` directly (without going through `ErrorDialog`). 
* Depending on the props passed to `ErrorDisplay` (and sometimes these are drilled through `ErrorDialog` or other intermediate components), the results are different, and not always what you might desire. That means we can't fix https://github.com/hypothesis/lms/issues/2997 in a direct way (in `ErrorDisplay`) without potentially borking other error states.
* `ErrorDisplay` has some Byzantine logic around deciding what kind of error messaging to display, which is in turn affected by some possibly-un-useful default error messages set on, e.g. `APIError`. Based on the combinations of props possible to `ErrorDisplay` other components, this becomes a morass.
* Most of the error-related UI is still using the local LMS Dialog implementation and styling. This isn’t a _bug_, it’s just a task that needs to be handled: conversion of the Error-related dialogs over to using the shared `Modal` from the `frontend-shared` package.
	* However, there are cases in the LMS UI where an error needs to be rendered in a modal that cannot be dismissed. Therefore, … needs to be tackled before this switchover can occur.

A path to untangling this (some of this can be parallelized):

* [x] As much as is feasible, document how to get into various error states and get screenshots of error states. See https://github.com/hypothesis/lms/pull/3160
* [x] Decompose `ErrorDisplay` ; refactor such that subcomponents (e.g. `ErrorDetails`, perhaps) are exported as well. Several error-related components use `ErrorDisplay`, but really only want to render error details, e.g. This might be a temporary step, but will help clean up targeted error messages like in https://github.com/hypothesis/lms/issues/2997 and give developers some finer-grained control about what shows up in an error dialog.
* [x] Provide a non-closeable Modal in the shared package: https://github.com/hypothesis/frontend-shared/issues/139
* [x] Evaluate whether `APIError` should set a default error message or not, and whether “An unknown error occurred” is _ever_ a useful error message to display to a user.
* [x] Convert `ErrorDialog` to use shared-package modal, and update style rules (likely greatly simplified). Take advantage of the Modal’s overflow context or use the `Scrollbox` component to better normalize the size of error dialogs. https://github.com/hypothesis/lms/issues/3106
* [x] Convert other error-ish dialogs to use shared-package Modal.
* [x] Remove local implementations of Dialogs, etc. from LMS
* [x] Create pattern library examples in the LMS app of different error state UI treatments to help make maintenance easier in the future

**Comment by lyzadanger** [comment]
DONE FINALLY DONE! YAY!
