### ISSUE TITLE
Add an "application_instance_id" FK to tables that currently use `consumer_key`

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#3719]
## Action plan

- https://github.com/hypothesis/lms/issues/3719
  - [x] https://github.com/hypothesis/lms/pull/3748
  - [x]  https://github.com/hypothesis/lms/pull/3749
  - [x]  https://github.com/hypothesis/lms/pull/3750
  - [x]  https://github.com/hypothesis/lms/pull/3751
  - [x]  https://github.com/hypothesis/lms/pull/3752
  - [x]  https://github.com/hypothesis/lms/pull/3753
  - [x]  https://github.com/hypothesis/lms/pull/3767
  - [x]  https://github.com/hypothesis/lms/pull/3768
  - [x] https://github.com/hypothesis/lms/pull/3779
  - [x] https://github.com/hypothesis/lms/pull/3780
  - [x] https://github.com/hypothesis/lms/pull/3781
