### ISSUE TITLE
Canvas LTI 1.3 Support

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/lms#3971]
Current functionality for Canvas should work. That means

- [x] Canvas users can edit the assignment (as expected, given caveats with module items)
- [x] Student submissions should submit to speedgrader
- [x] Canvas API keys should work on groups and files
- [x] Course copy should work (as expected, given caveats with groups and module items)

## Tasks

- [x] #3965 
- [x] #3966 
- [x] Deeplinking in Canvas
