### ISSUE TITLE
Add organizations to the DB model

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4200]
In order to track organisations we need to agree and create a DB model for them.

## Tasks

 * [x] https://github.com/hypothesis/lms/pull/4329
 * [x] https://github.com/hypothesis/lms/pull/4330
 * [x] https://github.com/hypothesis/lms/pull/4412

### Add `organization` table

| Field | Type | Notes |
|--------|---------|---------|
| `id` | int -  Primary key |
| `name` | string | For humans
| `parent_id` | FK to `organization.id` | _(optional)_ Not for now, but we'll want it soon
| `public_id` | string | A UUID for putting in external systems
| `settings` | JSON | The usual settings object
| `created` | datetime
| `updated` | datetime

### Modify `application_instances`

Add a FK to `organization.id`

   * This can be nullable, but nullable in this context means "not launched yet" rather than being a valid long term state
   * **Alternative:** Create shadow orgs and destroy them on merge? This way the FK is always populated?

See:

 * https://github.com/hypothesis/lms/issues/4202

### Modify `registrations`

Anything to do here? Should we prevent anything or have constraints around application instances and registrations belonging to the same org?

What if you want to move org, what then?

**Comment by jon-betts** [comment]
Done! This doesn't do anything by itself, but it's a building block and it's deployed.
