### ISSUE TITLE
Find out if Postgres' materialized views will solve our needs for real-time data

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4513]
Our users do not want to wait around for a long time when getting answers to their questions. We also do not want to hit any Metabase timeouts (2 minutes), but as a users patience will run out long before that, the real limit is much lower: a few seconds at most. In the project definition we describe the requirement as "instant" access.

Some of our tables (like `h's annotation table) are very slow to query. We believe that by using [Postgres' materialized views](https://www.postgresql.org/docs/current/rules-materializedviews.html) we can create tables which:

 * Represent the same data in a more query friendly way - with better indexes and sensible data structures
 * Create new partially aggregated data

Together we believe this should allow us to get reports in a prompt way.

In order for this to work we need to validate our assumptions.

## The definition of "instant"

Instant access is impossible, so by this we assume that we mean:

 * When a user starts a query, they have to wait no longer than a few seconds for a result
 * This **_does not_** mean the data they are viewing is real-time
 * The data may, for example, have been calculated last night

## Assumptions

 * [x] We can easily deploy new materialized views
 * [x] We can easily trigger recreation of materialized views
 * [x] We can use materialized views which are composed from other materialized views
 * [x] Data in materialized views is available in read replicas
 * [x] We can maintain access to the data as it is rebuilt - so we do not have any down time while it is updated
     * You can still read and write from the underlying tables (like annotation) while a view is being built
     * You can try and build "CONCURRENTLY", but it requires at least one unique index
     * For some tables there is no unique index to be had? Or can we create one?
     * It seems to be about 2x slower to do it concurrently for annotations (faster for others?)
 * [x] We will not disrupt live users while creating the views
     * Trying to read from a building materialized view hangs until it's done (this isn't great)
    * Not sure about performance - it's an intensive task
    * **???** - Honestly we don't know. We may have to run small scale trials in live to find out
 * [x] Creating even the slowest views will not take more than about 10 minutes
    * **NOPE** - The minimum on the annotation table is about 13 minutes
    * 15 minutes if you want to configure it concurrently and 30 minutes to do a concurrent update
    * Most other aggregations over it are 1-3 minutes

## Tasks

 * [x] Get a read-write copy of `h` data (as the annotation table is the worst offender)
 * [x] Get a way to execute SQL queries against it
 * [x] Attempt to work answers to as many of the above as possible
 * [x] Get a read replica of our read-write `h` data
 * [x] Find out if data will sync etc.

**Comment by indigobravo** [comment]
### Temp Devel Instance

A Ubuntu EC2 server has been provisioned with access to the [**Temp RDS Instances**](https://github.com/hypothesis/lms/issues/4513#issuecomment-1273268008). Using h-ssh you can connect like this:

```
h-ssh 10.1.1.165
```

Running the following will set 4 environment variables.

```
source /home/ianburden/setenv.sh
```

|Name|Description|
|:-|:-|
|lms_db_password|The password for lms-prod database|
|h_db_password|The password for the h database|
|h_db_dsn|A PostgreSQL DSN for the h database|
|lms_db_dsn|A PostgreSQL DNS for the lms-prod database|

**Comment by jon-betts** [comment]
I've written up some conclusions here:

 * https://github.com/hypothesis/numberwang/blob/a00019136c1fce03703b6231f5793028cabbdda5/examples/materialized_views/thoughts.md

Basically:

 * They give us the performance we need
 * They seem good for aggregations
 * We might want to try something else for the main annotation table
 * Impact on a live system is uncertain
