### ISSUE TITLE
Find out which forms of Metabase syncing for reports will work for us

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4514]
Depending on [the design of our internal data offering](https://www.notion.so/Project-Business-Intel-Documentation-0c826766d5404ec4912a1caf15e10336) we will need one or more types of syncing of reports which are repeated across regions.

We will want the same types of reports available in Canada as we have in the US. We also don't want to repeat ourselves or maintain these by hand. Therefore we believe we will be able to use

### Separated regional Metabase instances

 * [ ] We can sync models, dashboards, questions etc. from one Metabase to another
 * [ ] We can leave audit data alone
 * [ ] We can do this in such a way as keep different DB connection details (for the regions)
 * [ ] We can sync users and permissions (does not need to be the same mechanism, can Google auth help us here?)

### Global Metabase

If we are using a single metabase instance we will need to perform similar but different actions. In the case of a single metabase instance we need to copy dashboards and queries from one section of itself to itself.

 * [ ] We can copy models, dashboards, questions etc. from one section in a Metabase instance to itself in another
 * [ ] We can preserve other reports without copying or changing them
 * [ ] We can do this in such a way as keep different DB connection details (for the regions)

### Other questions

 * [ ] _Bonus points_ - If this has a representation we can put into Git, that would be good to know
 * [ ] Can we get an evaluation license or something to test out the enterprise paid for syncing stuff?
 * [ ] What about disaster recovery? Maybe it's irrelevant, just backup the master DB.

## Options

We should consider how good or bad duplicating and managing by hand would be. We probably won't be doing this as devs? (I hope) Could someone else. We should seriously consider this.

Are there are semi automated things? Bulk actions in Metabase?

## Preliminary research

Paid metabase provides https://www.metabase.com/learn/administration/serialization which exports mostly all contents of one metabase into yaml files.

An alternative would be to build something similar using the API.

The built in solution has the advantage of keeping the IDs of all entities the sames, this simplifies sync (update vs inserting) but might be also very useful for next stages when we try to build product around met abase (question ID X it's the same in US/CA).

In the serialization solution connection details are exported, we'd probably need to either exclude them or have some process to change them to the ones required in each enviroment.

## Tasks

 * We should be able to use local Metabase instances for most of this

**Comment by marcospri** [comment]
Closing this, we can re-open if we are interested in it again.

For now, for internal reports, the solution is to not do any kind of metabase syncing as we have only one global instance.
