### ISSUE TITLE
Coalesce data from all regions to provide an overview of organization activity

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4518]
# Note

This ticket is out of date after our new ideas of structuring the project

# Anyway...

After these tickets:

 * https://github.com/hypothesis/lms/issues/4516
 * https://github.com/hypothesis/lms/issues/4517

We should have data about organization activity in each region, but there is a desire to have an overview for all regions.

This involves merging the aggregated data from the regions in such a way as to provide a report which allows us to find the top organizations by various criteria.

This requires us to have a report which mostly mirrors the results of the regional activity report, but includes all regions at once. It should also include a region column.

## Requirements

 * The answer should be available nearly instantly
 * We will not sync the individual row level data from regions (only aggregated values)
 * This does not require a lot of maintenance when adding a new region
 * The data is up to date, as of at least a day ago

### Questions this lets us answer

All the same questions as before, but over all regions.

## Tasks

 * [ ] Create the required global Metabase instance (if we are using a single instance this might already have happened)
 * [ ] Create a Postgres instance for the global instance to store rollups
 * [ ] Demonstrate a method to sync the satellite data into the store
 * [ ] Call the method in a CI/CD pipeline
 * [ ] Create the report

### WIP tasks (We're discussing this now)

 * [ ] De-risk the annotation table - create the GHA action
 * [ ] Add the FDW extension to LMS Postgres
 * [ ] Add FDW connection in LMS to H
 * [ ] Plan the required aggregations on paper to create the organization activity report
 * [ ] Do what we can in-region
 * _... pause ..._ Assume something happens here to sync data globally

**Comment by jon-betts** [comment]
This has been superseded by smaller more specific tickets after our spikes were done
