### ISSUE TITLE
Rewrite the app's OAuth 2.0 (for Canvas Files) support

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#460]
This issue describes a rewrite of the app's Canvas Files (and OAuth 2.0) support in order to solve multiple issues, including:

* Code reusability issues:
  * With the code as it is, it won't be easy to add support for other file storage (Blackboard, Moodle). When we want to do that, we will end up having to rewrite the code anyway
* Usability issues:
  * [Asking the user to click <samp>Authorize</samp> on every page load](https://github.com/hypothesis/lms/issues/171)
  * There are lots of UX-related issues with the content item selection dialogs themselves but we _don't_ propose to address those as part of this issue
  * Complete lack of error handling. A lot of different requests get made from our JavaScript to our server and from our server to the Canvas API as part of our OAuth 2 support. The app has no error handling for any of these. If anything goes wrong with any of these requests the app crashes. There's no validation of OAuth-related requests and responses at all. As well as being bad UX this creates a lot of noise in our crash reporting system.
* Scalability issues:
  * [The `oauth_state` table grows forever](https://github.com/hypothesis/lms/issues/454) and will eventually crash the app as usage increases
* Lots of OAuth-related crashes that users are seeing, including:
  * [Crash when cancelling Canvas authorization](https://github.com/hypothesis/lms/issues/455)
  * Various others seen in Sentry that don't have GitHub issues yet
* Security issues, including:
  * The app [does authorization in an iframe](https://github.com/hypothesis/lms/issues/281) which is insecure (phishing attacks, click-jacking, ...) and could get us blocked from Canvas OAuth one day
  * Creating a huge number of access tokens in the Canvas instance (one each time any user launches an assignment). Definitely bad behavior and could be noticed by Canvas admins.
  * The app's Canvas Proxy API, as implemented currently, is essentially a security downgrade attack on the Canvas API and could make users accounts vulnerable
  * Access and refresh tokens in the DB aren't encrypted
* Incompleteness:
  * No support for reusing access tokens
  * No refresh token support
  * No error handling
  * No UX details or niceties
* Code changeability issues:
  * The current OAuth code is very tangled up with the LTI launch views and makes it very difficult or impossible to make simple changes such as adding LTI launch validation or cleaning up the views code. This is slowing us down a lot or outright stopping us, when trying to make changes to the app.

See Also
--------

* [Canvas API OAuth 2 docs](https://canvas.instructure.com/doc/api/file.oauth.html)
* OAuth 2 Authorization Code Grant Type (Google it!)

* * *

What needs to be implemented:

Authenticating to Our Server Using a JWT
----------------------------------------

Whenever a page rendered by our app makes a request to our server (for example a
form submission, or an XHR request from JavaScript code) our server needs to
know **which LTI user made the request**. In other words, which LTI user the
page that made the request was rendered for.

When we receive an LTI Launch Request from Canvas (or any LMS) we know which LTI
user made the request from the request's (signed) LTI Launch Params.

But what about the pages that we send back to the user's browser in response to
an LTI Launch Request? These pages might contain HTML forms that send form
submission requests to our server, or JavaScript code that makes XHR requests
to our server. When it receives these subsequent requests our server still needs
to know which LTI user the request belongs to but since these aren't LTI launch
requests (`request.params` doesn't contain LTI launch params) the server can't
authenticate the user from the LTI launch params.

So the server needs another authentication mechanism for these subsequent
requests:

1. On receipt of any successful LTI Launch Request, after the server has verified
   the request's signature and authenticated the LTI user, it should:
   
   - [x] Render into the HTML of the page a signed JWT that identifies the LTI user.

<details>
<summary>Refreshing JWTs</summary>

<p>The above mechanism allows the page to make authenticated requests but it
<em>doesn't</em> allow subsequent pages (navigated to from the original LTI launch
response page) to make authenticated requests as those pages won't contain a
JWT. The server only renders JWT's into the immediate LTI launch response
pages. (It only renders a JWT into the response if the request was a valid LTI launch request.)</p>

<p>We could address this by having the server render a fresh JWT for the same
user into each response to a request containing a valid JWT.
But this would mean that an attacker could continuously refresh a stolen JWT
and remain authenticated forever.</p>
</details>

Getting a New Access Token When Creating a Canvas File Assignment
-----------------------

1. When the teacher creates a Hypothesis assignment inside Canvas, the app
   renders the **Content Item Selection Page**.

1. When the user clicks on the <samp>Use Canvas File</samp> button the Content Item Selection Page should:

   - [x] Show the **Canvas Files Dialog**
   - [x] Open Canvas's **Authorization Page** in the **Popup Window**.

1. If the user clicks <kbd>Authorize</kbd> then Canvas redirects the Popup
   Window to our **Redirect URL** with the **Authorization Code** in the
   URL's query string. This is the **Redirect URL Request**. It's a request
   made by the Popup Window (on Canvas's instruction) to our server.

1. When it recieves the Redirect URL Request our **Redirect URL View** should:

   - [x] Send the **Access Token Request** to the Canvas API.
       
     This is a server-to-server HTTP request. This request can just be made
     synchronously, during the processing of the Popup Window's request to our
     Redirect URL.

1. When it receives a valid Access Token Request from us the Canvas API sends
   the **Access Token Response** back to us.
   
   When our server receives the successful Access Token Response it should:

   - [x] Write the **Access Token** and **Refresh Token** to the DB.
       
     In the DB the token needs to be associated with the specific LTI user to
     which it belongs. We could use `(tool_consumer_instance_guid, user_id)`
     to identify the user in the tokens table, for example. Or maybe
     `(oauth_consumer_key, user_id)`.

     We should probably have an `LTIUsers` table with one row for each LTI user
     and a relationship between the LTI users and tokens tables.

     Any existing tokens table row for this user in the DB should be overwritten.

   - [x] Send back a successful response to the Popup Window in the **Redirect
     URL Response**.

     The Redirect URL Response doesn't need to actually contain anything (e.g.
     it doesn't need to contain an access token or a JWT). It's just a `200 OK`
     response that lets the Popup Window know that the server now has an
     access token for this user.

1. When the Popup Window receives the successful Redirect URL Response from our
   server it should:

   - [x] Communicate this success back to the Canvas Files Dialog.

1. When the Canvas Files Dialog receives the success notification from the Popup
   Window it should:

   - [x] Send the **List Canvas Files XHR Request** to our **Canvas Proxy API**,
     including the JWT in the request for authentication

1. When our Canvas Proxy API receives the List Canvas Files XHR Request it should:

   - [x] Send the **List Canvas Files Server Request** to the Canvas API.
   - [x] Receive the successful **List Canvas Files Server Response** from the
     Canvas API, and send it back to the Canvas Files Dialog as the response to
     the original List Canvas Files XHR Request

1. When the Canvas Files View receives the successful List Canvas Files XHR
   response it should:

   - [x] Render the **Canvas File List Dialog** so that the user can choose the file for the assignment.

1. When the user selects a Canvas File for the assignment... (whatever the app does currently, it either sends the file back to Canvas or stores it in its own DB, depending)

Getting a New Access Token When Launching a Canvas File Assignment
------------------------------------------------------

The app also needs an Access Token in order to _launch_ a Canvas File assignment.
On assignment launch, if the assignment is a Canvas File assignment, it needs to
go through a similar process as when creating an assignment (but not exactly
the same):

1. Unlike with other kinds of assignment, when the user launches a Canvas Files
   assignment we don't yet know the **Canvas File Public URL** so we can't
   construct the **Via URL** for the **Via iframe**'s `src` attribute.
   The **Assignment Page View** should:

   - [x] Load the page with the Via iframe's `src` attribute set to some local
     (LMS app) URL for a page that indicates that the assignment is still
     loading and that the user should see the Popup Window.

1. As soon as the **Assignment Page** loads for a Canvas Files assignment it
   should:

   - [x] Open Canvas's **Authorization Page** in the **Popup Window**.

1. When the user clicks <kbd>Authorize</kbd> then Canvas redirects the Popup
   Window to our **Redirect URL** with the **Authorization Code** in the
   URL's query string (the **Redirect URL Request**).

1. When it recieves the Redirect URL Request our **Redirect URL View** should:

   - [x] Send the **Access Token Request** to the Canvas API.
       
1. When it receives a valid Access Token Request from us the Canvas API sends
   the **Access Token Response** back to us.
   
   When our server receives the successful Access Token Response it should:

   - [x] Write the **Access Token** and **Refresh Token** to the DB.
       
   - [x] Send back a successful response to the Popup Window in the **Redirect
     URL Response**.

1. When the Popup Window receives the successful Redirect URL Response from our
   server it should:

   - [x] Communicate the success notification back to the Assignment Page.

1. When the Assignment Page receives the success notification from the Popup Window it should:

   - [x] Send the **Get Public URL XHR Request** to our **Canvas Proxy API**,
     including the JWT in the request for authentication

1. When our Canvas Proxy API receives the Get Public URL XHR Request it should:

   - [x] Send the **Get Public URL Server Request** to the Canvas API.
   - [x] Receive the successful **Get Public URL Server Response** from the
     Canvas API, and send it back to the Assignment Page as the response to
     the original Get Public URL XHR Request

1. When the Assignment Page receives the successful Get Public URL XHR
   response it should:

   - [x] Change the `src` attribute of thw Via iframe to the correct Via URL.
     This will cause the assignment to be rendered.

Reusing Access Tokens
---------------------

We don't want to make the user have to re-authorize our app in a popup window
every time they launch it.

Above we've described the lengthy process (called an OAuth 2 Authorization Code
Grant) for getting an access token for a user, and how that process needs to be
applied to both the content item selection and the assignment pages whenever
Canvas files are involved.

We only want to go through this authorization process if we don't already have
an access token for the user in our DB, or if our access token for the user
has expired.

If we already have an unexpired access token for the user in our DB then we
should reuse it instead of going through the authorization process again.

1. During Content Item Selection, when the user clicks on the
   <samp>Use Canvas File</samp> button, the app should:

   - [x] Reuse a previously-saved Access Token for this user from our DB, if we
     have one that isn't expired, instead of opening the Popup Window.

   - [x] Detect when a previously-saved Access Token for this user has expired,
     and trigger the re-authorization process.

     For example the page might make the **List Canvas Files XHR Request**,
     causing the server to make the **List Canvas Files Server Request**, and on
     recieving an authorization error from the Canvas API the server would send
     an authorization error back to the page which would trigger the
     re-authorization process.
     
     In cases where the server has no saved access token for the user at all it
     could just send the authorization error back to the page immediately,
     without even attempting the List Canvas Files Server Request. So the page
     could just always blindly attempt the List Canvas Files XHR Request and
     trigger the authorization popup window if it recieves an authorization
     error response.

1. When launching a Canvas Files assignment the app should:

   - [x] Reuse a previously-saved Access Token for this user from our DB, if we
     have one that isn't expired, instead of opening the Popup Window.

   - [x] Detect when a previously-saved Access Token for this user has expired,
     and trigger the re-authorization process.

     For example we might try to make the **Get Public URL XHR Request**
     and, on recieving an authorization error response, trigger the
     re-authorization process.

Using Refresh Tokens
--------------------

Canvas access tokens expire after one hour so even if we implement reusing
access tokens (see above) we'll still be asking the user to re-authorize our app
in a popup window every hour. To really reduce how often we ask the user to
re-authorize our app we need to use refresh tokens.

1. During either a Content Item Selection or a Canvas Files Assignment launch,
   if the app decides that its saved access token has expired (for example
   because we get an authorization error from the Canvas API when we try to use
   it) the app should:

   - [x] Attempt to get a new access token without bothering the user by sending
     a **Refresh Token Request** to the Canvas API (server-to-server),
     receiving the Canvas API's **Refresh Token Response**, and saving the new
     Access Token and Refresh Token to the DB just as it would do on receipt of
     a successful Access Token Response.
     
   - [x] After using the Refresh Token to get a new Access Token the server
     should go ahead and make the required Canvas API request (for example the
     List Canvas Files Server Request or the Get Public URL Server Request) and
     send back the response just as it would have done if the Access Token had
     not been expired.

     This means that the page that is calling the Canvas Proxy API can be
     blissfully unaware of the fact that a Refresh Token was used.

  - [x] The server should still send back an authorization error (which will
    trigger opening the Popup Window for re-authorization) if the Refresh Token    
    Request fails due to a timeout or an error response from the Canvas API.

<details>
<summary>Refreshing Access Tokens in the Background</summary>
<p>This is a bonus feature but since the server has access tokens and refresh
tokens for all the users in its DB, and it knows when these access tokens
expire (after one hour, for Canvas access tokens), the server could have a
background worker that always keeps all the tokens refreshed independent of any
user interaction with our app.</p>

<p>This would further reduce how often we have to ask users to re-authorize and it
would also make LTI launches faster as we're not doing Refresh Requests during
the launches.</p>

<p>This isn't striclty necessary, though.</p>
</details>

Details and Error Handling
--------------------------

Below is a long list of UI details and error handling that need to be gotten
right to make this a good user experience. These can all be omitted from a
first release of the feature as the current OAuth 2 support has none of these
so it would still be an improvement on what's there. Each of these details can
then be added in subsequent iterations.

### The Content Item Selection Page When The Popup Window Is Open

When the user clicks on the <samp>Use Canvas File</samp> button on the app's
Content Item Selection Page and the app opens Canvas's Authorization Page in the
Popup Window, the Content Item Selection page is still open and visible in the
original window/tab. The user can still see it. The user might change back to
the original tab, or might even "lose" the Popup Window (e.g. beneath
another window) and continue trying to use the original tab.

So the Content Item Selection page needs to have sensible behaviour when the
Popup Window is open. The Content Item Selection Page should:

- [x] Change its UI to indicate that it's waiting for authorization from the Popup Window
- [x] Include a link to the Popup Window
- [x] Include a button for aborting the Canvas file selection process and going
  back to the File Choices view. (In the current UI this button is labelled
  <samp>Cancel</samp>.)
  - [x] Clicking <samp>Cancel</samp> should close the Popup Window

Here's a screenshot of Paypal doing this sort of thing:

![screenshot from 2019-02-17 23-20-35](https://user-images.githubusercontent.com/22498/53023655-8df4b580-3455-11e9-831a-26271ceadfe9.png)

### The Assignment Page When The Popup Window Is Open

Similar to the Content Item Selection Page when the Popup Window is open, the
Assignment Page should:

- [x] Change its UI to indicate that it's waiting for authorization from the Popup Window
- [x] Include a link to the Popup Window

### The Canvas Files Dialog When The User Cancels Authorization

When we open Canvas's Authorization Page in the Popup Window the user might
close the Popup Window without clicking <kbd>Authorize</kbd> or they might
click <kbd>Cancel</kbd> instead of <kbd>Authorize</kbd>. When this happens:

- [x] The Popup Window should close
- [x] The Canvas Files Dialog should show an <samp>Authorization was cancelled</samp> error message
- [x] The Canvas Files Dialog should show a <kbd>Retry</kbd> button that opens the Popup Window anew
- [x] The Canvas Files Dialog should continue to show its <kbd>Cancel</kbd> button for aborting the Canvas file selection process and going back to the File Choices dialog.

### The Assignment Page When The User Cancels Authorization

Similar to with the Canvas Files Dialog, when the Assignment Page opens the
Popup Window the user may close it or click <kbd>Cancel</kbd> instead of
<kbd>Authorize</kbd>. When this happens:

- [x] The Popup Window should close
- [x] The Assignment Page should show an <samp>Authorization was cancelled</samp> error message
- [x] The Assignment Page should show a <kbd>Retry</kbd> button that opens the Popup Window anew

### When The Access Token Request Fails

Whenever the user clicks <kbd>Authorize</kbd> on Canvas's Authorization Page
(whether during content item selection or during assignment launch) and our
server receives an authorization code from Canvas and uses it to make an
Access Token Request to Canvas, this Access Token Request may timeout or receive
an error response from Canvas.

When this happens:

- [x] The server should send an error response back to the Popup Window
- [x] The Popup Window should remain open and should indicate to the user that
  an error happened
- [x] The Popup Window should include a <kbd>Retry</kbd> button that, when
  clicked, redirects the Popup Window back to Canvas's Authorization Page again
  (restarting the process)

### When Verifying Our JWT Signature Fails

When our server receives any request (for example a form submission or an XHR
request) with a JWT in it it should verify the signature of that JWT. If
verification fails it should:

- [x] Send back an error response

### When the List Canvas Files Server Request Fails

When our server receives the List Canvas Files XHR Request and makes the List
Canvas Files Request to the Canvas API the request might timeout or receive an
error response from Canvas. When this happens the server should:

- [x] Send back an error response to its caller (the Canvas Files Dialog)

### When the Get Public URL Server Request Fails

When our server receives the Get Public URL XHR Request and makes the Get
Public URL Server Request to the Canvas API the request might timeout or
receive an error response from Canvas. When this happens the server should:

- [x] Send back an error response to its caller (the Assignment Page)

### When the List Canvas Files XHR Request Fails

When the Canvas Files Dialog receives an error response to the List Canvas Files
XHR Request, or the request times out, the dialog should:

- [x] Show the user an error message
- [x] Include a <kbd>Retry</kbd> button that re-sends the request

### When the Get Public URL XHR Request Fails

When the Assignment Page receives an error response to the Get Public URL XHR
Request, or the request times out, the dialog should:

- [x] Show the user an error message
- [x] Include a <kbd>Retry</kbd> button that re-sends the request

Terminology
-----------

### The Content Item Selection Page

The page that our app shows when the instructor is creating an assignment, to let them choose the document for the assignment.

![screenshot from 2019-02-19 14-52-05](https://user-images.githubusercontent.com/22498/53024001-2723cc00-3456-11e9-8a48-68ea296bbb54.png)

### The Canvas Files List Dialog

Part of the Content Item Selection page. A dialog that shows the user the list of Canvas files to choose from:

![screenshot from 2019-02-19 14-52-30](https://user-images.githubusercontent.com/22498/53024114-50dcf300-3456-11e9-8768-927f3c4afa32.png)

### Canvas's Authorization Page

The page that we redirect users to that asks them to click <kbd>Authorize</kbd> so that we can get an Access Token for the Canvas API.

![screenshot from 2019-02-19 14-51-47](https://user-images.githubusercontent.com/22498/53024023-30149d80-3456-11e9-9956-dce5e278ccc8.png)

### The Popup Window

Popup window in which we show the Authorization Page.

It's important to show this page in a popup window not inside Canvas.

### The Assignment Page

The page that finally shows the assignment to the user. Looks like this:

![screenshot from 2019-02-19 14-53-05](https://user-images.githubusercontent.com/22498/53025298-96022480-3458-11e9-9393-67524c7436d2.png)

### The JWT

A token created by our server that contains a unique identifier for an LTI user. For example a `(tool_consumer_instance_guid, user_id)` tuple, or a `(oauth_consumer_key, user_id)` tuple. This JWT can be used instead of LTI launch params in subsequent form submission or XHR requests to authenticate to our server as the LTI user.

The JWT will have a short TTL so that, if stolen, it can only be used within a
short time window.

The JWT contains no sensitive information so it doesn't need to be encrypted.
But it does need to be tamper-proof and unforgeable, so it should be signed by
the server.

We're using a JWT rendered into the page's HTML instead of a cookie,
`localStorage` or `sessionStorage` to avoid any problems with cookie disabling,
browser rules about third-party cookies (which also affect `localStorage`),
etc.

### Our Canvas Proxy API

A JWT-authenticated API that our server provides for JavaScript on our pages to call. Makes Access Token-authenticated requests to the Canvas API (using Access Tokens saved in the server's DB) and sends back the responses to the JavaScript caller.

Also uses Refresh Tokens to get new Access Tokens as necessary, without the JavaScript caller needing to be aware of this.

Also sends back authentication errors to the JavaScript caller if we have no Access Token for this user, or if both the Access Token and Refresh Token have expired. The JavaScript responds to these errors by triggering re-authorization in the Popup Window.

### Our Redirect URL

A URL of our LMS app that Canvas redirects the Popup Window to after the user clicks <kbd>Authorize</kbd>. 

The Redirect URL is fixed becaue it's part of our install-time LTI app configuration.

### Redirect URL Request

The `GET` request that the user's browser (the Popup Window) sends to our server when Canvas redirects the Popup Window to our Redirect URL.

### The OAuth 2 Authorization Code

A code that Canvas puts in a query param on this URL and we then use the Authorization Code to get an Access Token and Refresh Token.

### The OAuth 2 Access Token

A token that we receive from the Canvas API that we can use to authenticate to the Canvas API on behalf of a specific Canvas user.

Access tokens expire after one hour.

### The OAuth 2 Refresh Token

A token that we receive from the Canvas API along with the Access Token. When an Access Token has expired we can use its corresponding Refresh Token to try to get a new Access Token.

We don't know when Canvas refresh tokens expire.

### The Access Token Request

The request that we send to Canvas in which we exchange the Authorization Code for an Access Token and Refresh Token.

See <https://canvas.instructure.com/doc/api/file.oauth.html>

### The Access Token Response

Canvas's response to the Access Token Request, that includes the Access Token and Refresh Token in the response body.

See <https://canvas.instructure.com/doc/api/file.oauth.html>

### The Refresh Token Request

The request that we send to Canvas in which we exchange a Refresh Token for a new Access Token and Refresh Token.

See <https://canvas.instructure.com/doc/api/file.oauth.html>

### The Refresh Token Response

Canvas's response to the Refresh Token Request, that includes the new Access Token and Refresh Token in the response body.

See <https://canvas.instructure.com/doc/api/file.oauth.html>

### The Redirect URL Response

The response that our Redirect URL View sends back to the user's browser (the Popup Window) in response to its Redirect URL Request.

### The List Canvas Files XHR Request

JWT-authenticated request that List Canvas Files Dialog's JavaScript sends to the Canvas Proxy API to get the list of files.

### The List Canvas Files Server Request:

Access Token-authenticated request that the Canvas Proxy API sends to the Canvas API to get the list of files.

### The List Canvas Files Server Response

Response from the Canvas API to the Canvas Proxy API containing the list of files.

### The List Canvas Files XHR Response

Response from the Canvas Proxy API to the List Files Dialog containing the list of files.

### Canvas File Public URL

A publicly accessible download URL for the assignment's file. Via needs this URL so that it can proxy the file. Via need to proxy the file because CORS means that the browser (PDF.js running in the browser) cannot download the file itself via XHR. Via adds the necessary CORS header to make the file downloadable by PDF.js.

These public URLs from Canvas are short-lived so we need to get a new one from the Canvas API every time we launch a Canvas Files assignment.

### The Get Public URL XHR Request

JWT-authenticated request that our Assignment Page sends to our Canvas Proxy API to get the public URL for the assignment's document.

### The Get Public URL Server Request

Access token-authenticated request that our server sends to the Canvas API during a Canvas File assignment launch in order to get the public URL for the assignment's document.

Example:

```
curl "https://<canvas>/api/v1/files/1/public_url" -H "Authorization: Bearer <ACCESS_TOKEN>"
```

See <https://canvas.instructure.com/doc/api/files.html#method.files.public_url>.

### The Get Public URL Server Response

The Canvas API's response to our server's The Get Public URL Server Request. Example:

```json
{
  "public_url": "https://example-bucket.s3.amazonaws.com/...?AWSAccessKeyId=example-key&Expires=1400000000&Signature=example-signature"
}
```

See <https://canvas.instructure.com/doc/api/files.html#method.files.public_url>.

### The Get Public URL XHR Response

Response that our Canvas Proxy API sends back to our Assignment Page containing the public URL for the assignment's document.

### The Via URL

The URL of the Via iframe that the assignment page must contain. Looks like `https://via.hypothes.is/<CANVAS_FILE_PUBLIC_URL>` (plus some hard-coded query params on the end) where `<CANVAS_FILE_PUBLIC_URL>` is the Canvas File Public URL for the assignment. Getting that Canvas File Public URL is basically the entire problem here.

### The Via iframe

When it launches an assignment the LMS app's entire job is basically to render an HTML page containing an `<iframe>` whose `src` is the Via URL. Example:

```html
<iframe width="100%" height="100%" src="https://via.hypothes.is/<CANVAS_FILE_PUBLIC_URL>&amp;via.open_sidebar=1&amp;via.request_config_from_frame=https%3A%2F%2Fqa-lms.hypothes.is"></iframe>
```
### The Redirect URL View

Our Pyramid view that handles the Redirect URL Request.

### The Assignment Page View

Pyramid view that renders the assignment page in response to an LTI launch.

**Comment by robertknight** [comment]
Given how long the issue description was, I left some comments with Hypothesis: https://hypothes.is/groups/wqvn7Lar/hypothesis-reading?q=url%3Ahttps%3A%2F%2Fgithub.com%2Fhypothesis%2Flms%2Fissues%2F460

One product-related feature we know we want to deliver is support for using the file picker in non-Canvas LMSes. Blackboard and D2L appear to use OAuth from a brief look at their docs, so it seems that this work would be relevant for them as well. If we can take this opportunity to replace the generic Canvas proxy with a generic "list the files available to me in the LMS" API, then that would also make it easier to support other LMSes.

One general question I have is whether we could avoid the need for each student to approve access to files by re-using the teacher's access token at the point where we want to get a public URL for the file. If the access token is not shared with the client code, then perhaps this will be viable and could improve the experience for students?

**Comment by seanh** [comment]
> One general question I have is whether we could avoid the need for each student to approve access to files by re-using the teacher's access token at the point where we want to get a public URL for the file. If the access token is not shared with the client code, then perhaps this will be viable and could improve the experience for students?

Remember we need to use the access token and get the public URL on every launch (because the public URLs expire, and also may differ per user).

We don't want to do this. There's a number of problems with it.

* The teacher's account is a different account than the students, and has different permissions. For example access to more files. By using the teacher's access token on behalf of the student, we would end up showing students files they aren't supposed to see.

* When an access token expires (after one hour) and the refresh token has also expired (expiry time of Canvas refresh tokens unknown) then we need to make the user go through reauthorization again. All of the students would have to wait, and be stuck, until the teacher reauthorized us. (Plus how would we even implement that?)

It's just the wrong thing to do. You're only supposed to use a given access token on behalf of the user who owns that access token. When a student LTI launches us we're acting on behalf of that student and we should use that student's access token. Then we'll have no problems with permissions or with reauthorization.

**Comment by seanh** [comment]
Although I think we're still gonna end up having to do most of the work ourselves ([it's just the nature of OAuth 2 unfortunately](https://hyp.is/TF_ROjU8Eemi_n86l0LnFg/hueniverse.com/oauth-2-0-and-the-road-to-hell-8eec45921529)) we should definitely look in to what are the best OAuth 2 libraries, both Python and JavaScript, to help us.

**Comment by seanh** [comment]
This is done
