### ISSUE TITLE
Make the sign-up page private and redirect to a form

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4864]
We need to remove the publicly available sign-up page for application instances. This is to:

 * Ensure people who want to sign-up end up in our sales funnel
 * To ensure assignments are attached to organizations correctly
 * Cover some issues which arise from the details not being verified by us

## Tasks

* [x] https://github.com/hypothesis/lms/pull/4876
* [x] https://github.com/hypothesis/lms/pull/4888
   * The page is: https://web.hypothes.is/help/installing-the-hypothesis-lms-app/
* [x] https://github.com/hypothesis/lms/pull/4892
   * It is in the UI, but it can be in the service once the public view is gone
* [x] https://github.com/hypothesis/lms/pull/4890
   * Existing application instances in the wild which have no organizations and get launched still fall outside of our ability control
   * We can at least flag them so someone can take action

**Comment by jon-betts** [comment]
I think this is blocked on a discussion with Joe about policy here?

**Comment by jon-betts** [comment]
We have the go ahead to deploy
