### ISSUE TITLE
Add last updated to application instances and show it in the UI

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4965]
Some feedback from support people was that it's very good information to have some indication of when an application instance was last active.

This could take the form of the last launch associated with it for example. Another option is to have an updated field.

Both of these suffer in varying degrees by not existing. We have a create date field, but no update field, so if we added one it would only take effect from now. Last launch is a bit better in that it will cover last August to now.

Application instances are associated with groups however, which do have updated dates, so what we could do is create a conventional updated date and then back-fill it with the `MAX(created)` from associated groups. This would probably be a decent approximation. This also has the benefit of being simple (it's a field on the object you are looking at), rather than requiring any combining with other tables to work out.

## Proposed solution

 * Use the `CreatedUpdatedMixin` to add an updated field (as a separate book keeping measure)
 * Add a new `last_launched` field
 * Back-fill the values based on a query using last launch date

## Tasks

 * [x] https://github.com/hypothesis/lms/pull/4969
 * [x] https://github.com/hypothesis/lms/pull/4968
 * [x] https://github.com/hypothesis/lms/pull/4970
 * [x] https://github.com/hypothesis/lms/pull/5030
 * [x] https://github.com/hypothesis/lms/pull/5032

**Comment by jon-betts** [comment]
Done!
