### ISSUE TITLE
Support searching by application instance setting

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#5002]
Currently support staff search for application instances in Metabase. This is for a few reasons:

 * The search options in the admin pages aren't rich enough
 * The feedback from the pages isn't sufficient to find out what they need to know

Specifically application instance **_settings_** are used in a few distinct ways:

 * To indicate recent activity - This is now better handled with `last_launched`
 * To query by a specific settings presence or value
 * With an intent to change a setting

## Tasks

 * [ ] Add the ability to search for application instances by email or domain (separate ticket)
 * [ ] Add the ability to search for application instances by setting
 * [ ] When searching for a setting, display the value of that setting in the table as an extra column

#### Confirming or modifying settings

> Enable JSTOR for a customer

- You’d like to find some application instances so you can:
    - Confirm or modify a setting
- You start off in LMS admin pages by searching with:
    - Requesters email / domain only
    - And the setting you want to know about
    - (Optional) And a value you expect the setting to have
- The results you see have the setting specified
    - (Optional) If a value was specified they also have the value specified
- You can then click through to the application instance to complete the task 

#### Contacting customers with a specific setting

> find all (active) application instances where {"canvas": {"sections_enabled": true}}  in order to reach out to them to see if we can have their permission to turn sections_enabled to false

- You’d like to find some application instances so you can:
   - Contact all users with a specific setting
- You start off in LMS admin pages by searching with:
   - The setting you want to know about
   - And a value you expect the setting to have
- The results you see have the setting specified
   - And the value specified
- You can see the email addresses of the relevant users in the results to contact them
