### ISSUE TITLE
New LMSUser and LMSCourse tables

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#6575]
- [DD: New LMSUser and LMSCourse tables
](https://docs.google.com/document/d/1S0ordcbXc2W3pA3HZcEJ1tjmo9mBqbFOJcZ-qyKI75U/edit#heading=h.1cay7rutjflp)

- https://github.com/hypothesis/lms/pull/6568

### Tasks

- [x] Migration for LMSUser and related tables
- [x] Migration for LMSCourse and related tables
- [x] SQLAlchemy models for LMSUser and related tables
- [x] SQLAlchemy models for LMSCourse and related tables
- [x] https://github.com/hypothesis/lms/pull/6590
- [x] https://github.com/hypothesis/lms/pull/6589
- [x] https://github.com/hypothesis/lms/pull/6584
- [x] https://github.com/hypothesis/lms/pull/6579
- [x] https://github.com/hypothesis/lms/pull/6586
- [x] https://github.com/hypothesis/lms/pull/6612
- [x] https://github.com/hypothesis/lms/pull/6591
- [x] https://github.com/hypothesis/lms/pull/6592
- [ ] https://github.com/hypothesis/lms/pull/6593
- [ ] https://github.com/hypothesis/lms/pull/6594
- [ ] Relate assignments to lms_course (instead of or on top of the grouping relationship on assignment.course_id)
- [x] https://github.com/hypothesis/lms/pull/6856

- [ ] Switch all reads on the LMS codebase to the new code
- [ ]  Update report system and metabase queries to target the new tables
- [ ] Delete the code that maintains the old tables
- [ ] Delete the old tables.

### Follow up

- [ ] https://github.com/hypothesis/lms/pull/6560
