### ISSUE TITLE
MVP Canvas SpeedGrader Support 

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#658]
This is a sub-epic of the meta-epic [MVP Grading in Canvas, Brightspace and Blackboard](https://github.com/hypothesis/lms/issues/663)

## <del>BLOCKED</del>

This epic is blocked until:

- [x] Work currently underway to replace the app's Canvas Files and OAuth 2.0 support, and rewrite most of its views, is completed. Grading will be built on top of all the background work done there.

## User Stories

> As a Canvas instructor I want to grade Hypothesis assignments in SpeedGrader.
> 
> When I open an assignment in SpeedGrader Hypothesis should show me all of the selected student's annotations and replies on the selected assignment, so that I can assess their work and enter a grade into SpeedGrader's form.

## Parts

- [x] [SpeedGrader 0/n: Proxy API for making a submission to Canvas, for grading](https://github.com/hypothesis/lms/issues/846)

- [x] [SpeedGrader 1/n: Submit an LTI launch URL to Canvas for grading, when a student launches an assignment](https://github.com/hypothesis/lms/issues/655)

- [x] [SpeedGrader 2/n: Respond to SpeedGrader's LTI launches](https://github.com/hypothesis/lms/issues/656)

- [x] [SpeedGrader 3/n: Filter client to one student's annotations and replies](https://github.com/hypothesis/lms/issues/657)

## Proof of Concept

https://github.com/hypothesis/lms/pull/654
https://github.com/hypothesis/client/pull/1147

## Screenshot

Here's a screenshot of the client running in SpeedGrader, with the search bar (top right of client) filtered to the student being graded. (The assignment was to annotate a Black + Decker manual.)

![Screenshot from 2019-05-29 19-02-55](https://user-images.githubusercontent.com/22498/58580164-64ada780-8244-11e9-9031-a05b9d890da1.png)

**Comment by robertknight** [comment]
The MVP of SpeedGrader support in Canvas is now implemented. We're waiting for user feedback to guide us on how to improve it.
