### ISSUE TITLE
MVP Blackboard Grading Support

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#662]
This is a sub-epic of the meta-epic [MVP Grading in Canvas, Brightspace and Blackboard](https://github.com/hypothesis/lms/issues/663)

## <del>BLOCKED</del>

This is blocked until:

- [x] We have a fully working development instance of Blackboard, where we have full access and where it can be used with local development instances of our app.

- [x] We have more information about how grading for LTI apps works in Blackboard. See [SPIKE: Proof-of-concept MVP grading in Blackboard](https://github.com/hypothesis/lms/issues/660).

## User Stories

> As a Blackboard instructor I want to grade Hypothesis assignments in Blackboard's closest equivalent to Canvas's SpeedGrader.

## Parts

- [x] [Upsert grading information in DB on Blackboard assignment launch](https://github.com/hypothesis/lms/issues/946)
- [x] [Add proxy API for submitting grades to Blackboard](https://github.com/hypothesis/lms/issues/948)
- [x] [Add Blackboard grading UI elements](https://github.com/hypothesis/lms/issues/949)
- [x] [Implement changing focused student in Blackboard grading UI](https://github.com/hypothesis/lms/issues/950)
- [x] [Implement submitting grades in Blackboard grading UI](https://github.com/hypothesis/lms/issues/951)
- [x] [Show existing grades in Blackboard grading UI](https://github.com/hypothesis/lms/issues/952)
