### ISSUE TITLE
MVP Grading in Canvas, Brightspace and Moodle, Blackboard

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#663]
## <del>BLOCKED</del>

This epic is blocked until:

- [x] Work currently underway to replace the app's Canvas Files and OAuth 2.0 support, and rewrite most of its views, is completed. Grading will be built on top of all the background work done there.

## User Stories

<blockquote>"As LMS instructors we want to grade Hypothesis assignments using Canvas's SpeedGrader and its closest equivalents in Brightspace and Blackboard."</blockquote>

(For more specific user stories for each of Canvas, Brightspace and Blackboard see the individual cards linked below.)

## Plan

We'll deliver Canvas SpeedGrader support first, because:

1. It's going to be quickest and easiest because Canvas is the best-documented LMS; Canvas's SpeedGrader is the best for LTI grading; we're most familiar with Canvas; and we have a properly working Canvas test instance. We have a working proof of concept of how we want SpeedGrader integration to work, and we have actually implemented working Hypothesis SpeedGrader integration before, twice, in 2017.

2. Canvas is the most popular LMS, and so our highest-priority user need.

3. SpeedGrader integration is pure LTI and doesn't involve anything Canvas-specific.

   (This, however, doesn't mean that other LMS's support the necessary parts of LTI in the same way as Canvas does, or support them at all. It may in fact only work in Canvas, as far as we know.)

4. We hope that the work needed to support grading in Brightspace and Blackboard will be a superset of that needed for Canvas, such that all of our Canvas work will be reusable in Brightspace and Blackboard.

   This remains only a hope until we have more information about how grading works for LTI apps in Brightspace and Blackboard. It's possible that the work needed to support Bs and Bb is a partially or completely distinct set from that of Canvas. Even if that turns out to be the case though, we would still ship Canvas SpeedGrader support first for reasons 1 and 2 above.

## Parts

- [x] [MVP Canvas SpeedGrader Support](https://github.com/hypothesis/lms/issues/658)
- [x] [MVP Brightspace Grading Support](https://github.com/hypothesis/lms/issues/661)
- [x] [MVP Blackboard Grading Support](https://github.com/hypothesis/lms/issues/662)
- [x] MVP Moodle Grading Support (TBD)

**Comment by dwhly** [comment]
What are the #2 and #3 priority LMS for adding grading support-- in case there are different levels of complexity there.

**Comment by seanh** [comment]
Canvas is first priority, then Brightspace, then Blackboard

**Comment by klemay** [comment]
In a recent conversation with @jeremydean we've finalized the following priority order for grading in other LMSes once Canvas is done:

1. Blackboard
2. Moodle
3. Brightspace/D2L

Work on Blackboard will be blocked until https://github.com/hypothesis/lms/issues/849 is finished, but should _not_ be a blocker for working on Moodle (i.e., if Canvas is finished, it's time to build grading for other LMSes, and our hosted Bb instance isn't up and running yet, build grading for Moodle first).

**Comment by seanh** [comment]
Can you clarify what's meant by Blackboard? My understanding is that they have:

1. Blackboard Open LMS (formerly Moodlerooms) (https://www.blackboardopenlms.com/). We don't have a workable test instance for this but if it really is just themed Moodle then we could use our generic Moodle test site.

2. Blackboard Learn original or classic version. We used to have a limited test site for this but it seems to have gone away.

3. Blackboard Learn new version a.k.a "the Ultra experience". This is the one that we have access to a limited test site for at https://coursesites.com, but that test site is too limited for developing major features (no admin, doesn't work with localhost)

I'm not sure whether the test site that David is currently setting up in #849 is an instance of 1 or 2.

We're not sure how similar or different 1 and 2 are under the hood (they have completely different UX's though)

**Comment by klemay** [comment]
What we're setting up in #849 is an instance of [Blackboard Learn](https://help.blackboard.com/Learn), which is what we need to build for.

Ultra is the new/fancy UI Bb has rolled out for Blackboard Learn: https://help.blackboard.com/Learn/Instructor/Getting_Started/What_Is_Ultra

CourseSites is a free version of Blackboard Learn, with the Ultra UI, that gives no admin access - this is what we currently have: https://blackboard.coursesites.com/
