### ISSUE TITLE
Ideal Canvas SpeedGrader experience

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#664]
[MVP Canvas SpeedGrader Support #658](https://github.com/hypothesis/lms/issues/658) describes the minimal SpeedGrader experience that we'll ship first. This card goes beyond that and describes the ideal SpeedGrader experience that we could move towards in further iterations.

This represents our current view of what the ideal SpeedGrader experience would be. It might change when we receive user feedback.

FYI the ideal SpeedGrader experience as we understand it now (not withstanding any future user feedback we might get) is.

When Canvas launches out app in SpeedGrader:

- [ ] The sidebar should focus on (filter to) the one user's annotations and replies

- [ ] Auto scroll to the first annotation is nice to have but not a blocker

- [ ] No controls for switching assignment/document or user, let Canvas do that.

  We may end up needing them for other LMS's in future, but IMO these widgets likely need to be an LMS app feature not a client feature

- [ ] No way to "clear the search". There's no reason to do this when grading one student's submissions, it might be confusing, and most LTI apps (which would submit a Word file or PDF or something containing the one student's work) don't do it

- [ ] But we _do_ want to be able to expand other user's annotations or replies _that are in the same thread_ as one of the current user's as those may be relevant context for grading the current user.

  (Might not be LMS specific? Ability to expand rest of thread whenever a search filter is applied, without clearing the filter. You can sort of do it now but it works badly)

- [ ] Clear visual distinction between the current user's annotations and replies and those of other users which are shown only as context (may not be LMS-specific? Matching annotations vs others in thread)

- [ ] The teacher can (in the current proof-of-concept) make shared or private annotations or replies while grading but because of the way the filtering works the UX for this is buggy. Make annotating while a filter is applied not buggy (and this isn't LMS-specific)

- [ ] Realtime annotations

  I'm gonna skip the details to save myself time but realtime annotations (if students are still annotating while the teacher is grading) is problematic. Even outside of LMS realtime annotations are problematic both with and without a search filter applied. The UX is confusing and unhelpful. Plenty to fix here

Some things have been deliberately left out of the list above:

* We're ignoring stuff about late submissions for now, but one day we might want to do something to distinguish annotations that were made before the deadline from ones after. _Or_ just don't show ones from after.

  Annotations that get updated or deleted after the deadline may also be a problem.

  We don't know what the right solutions are yet.

* We're ignoring the idea of an "expanded" (activity-like) view (where the teacher sees the annotations and replies only, not the document) as opposed to sidebar-on-document, for now. Let's not design or implement this for SpeedGrader until we have strong feedback that users want it

^ That's it and I'm 95% confident that's exactly what teachers will want but we'll see what feedback we get

But I know Lyza wanted something generic to work on so I'm not requesting all this, just suggesting bouncer-links-to-users

**Comment by dwhly** [comment]
> want to be able to expand other user's annotations or replies that are in the same thread as one of the current user's as those may be relevant context for grading the current user.

Am I correct that this is now working?  I thought I saw this demo'd last week.

**Comment by seanh** [comment]
It does now work but I think it might be a bit buggy
